name: Push monorepo to Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release API
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'who-am-i-backend'
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: 'packages/api'
          HD_CLIENT_URL: 'https://who-am-i-frontend.herokuapp.com'
      - name: Release Web Client
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'who-am-i-frontend'
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: 'packages/web'
          HD_REACT_APP_SERVER_URL: 'https://who-am-i-backend.herokuapp.com'
